default:
  tags:
    - ronasit

variables:
  CD_PROJECT_ID: 1927

include:
  - project: 'spaces/gitlab-ci-cd/templates'
    ref: kubernetes
    file: 'laravel.yaml'

stages:
  - merge-request-prepare
  - .pre
  - analyse
  - tests
  - build
  - trigger
  - .post

tests:
  image: ghcr.io/ronasit/php-nginx-dev:8.3
